name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Extend when platforms are added 
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2
        with:
          version: "master"
      - name: Build and test
        shell: pwsh
        run: zig build test -Doptimize=ReleaseSafe
